name: Receive Dispatch Event

on:
  repository_dispatch:
    types:
      - my-custom-event

jobs:
  receive:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Display Payload
        run: echo "Received payload: ${{ toJSON(github.event.client_payload) }}"

