name: Receive Dispatch Event

on:
  repository_dispatch:
    types:
      - my-custom-event

jobs:
  receive:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Display Payload
        run: |
          echo "Key1: ${{ github.event.client_payload.key1 }}"
          echo "Key2: ${{ github.event.client_payload.key2 }}"


